PhotoSharingApplication/Controllers/PhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Globalization;
using PhotoSharingApplication.Models;

namespace PhotoSharingApplication.Controllers
{  
    [HandleError(View = "Error")]
    [ValueReporter]
    public class PhotoController : Controller
    {
        
        private PhotoSharingContext context = new PhotoSharingContext();

        // GET: Photo
        public ActionResult Index()
        {
            return View("Index");
        }

        [ChildActionOnly]
        public ActionResult _PhotoGallery(int number = 0)
        {
            List<Photo> photos;

            if (number == 0)
            {
                photos = context.Photos.ToList();
            }
            else
            {
                photos = (from p in context.Photos
                          orderby p.CreatedDate descending
                          select p).Take(number).ToList();
            }

            return PartialView("_PhotoGallery", photos);
        }

        public ActionResult Display (int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }

            return View("Display", photo);
        }

        public ActionResult Create()
        {
            Photo newPhoto = new Photo();
            newPhoto.CreatedDate = DateTime.Today;
            return View("Create", newPhoto);
        }

        [HttpPost]
        public ActionResult Create (Photo photo, HttpPostedFileBase image)
        {
            photo.CreatedDate = DateTime.Today;
            if (!ModelState.IsValid)
            {
                return View("Create", photo);
            }
            else
            {
                if (image != null)
                {
                    photo.ImageMimeType =
                    image.ContentType;
                    photo.PhotoFile = new
                    byte[image.ContentLength];
                    image.InputStream.Read(
                    photo.PhotoFile, 0,
                    image.ContentLength);
                }
            }

            context.Photos.Add(photo);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo == null)
            {
                return HttpNotFound();
            }
            return View("Delete", photo);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DeleteConfirmed (int id)
        {
            Photo photo = context.Photos.Find(id);
            context.Photos.Remove(photo);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        public FileContentResult GetImage (int id)
        {
            Photo photo = context.Photos.Find(id);
            if (photo != null)
            {
                return File(photo.PhotoFile,
                photo.ImageMimeType);
            }
            else
            {
                return null;
            }

        }


        public ActionResult SlideShow()
        {
            throw new NotImplementedException("The Slideshow action is not yet ready.");
        }
    }

}

PhotoSharingApplication/Views/Shared/_MainLayout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/Content/PhotoSharingStyles.css" />
</head>
<body>

    <h1 class="site-page-title">
        Adventure Works<br /> 
        Photo Sharing <br />
       
    </h1>

    <h2> Mobile Site</h2>
    <div class="clear-floats" />

    <div id="topmenu">
        @Html.MvcSiteMap().Menu(false, true, true)
    </div>
    
    <div id="breadcrumb">
        Current Location: @Html.MvcSiteMap().SiteMapPath()
    </div>
    
    <div>
        @RenderBody()
    </div>

</body>
</html>

PhotoSharingApplication/Views/Shared/_MainLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link type="text/css" rel="stylesheet" href="~/content/PhotoSharingStyles.css" />

</head>
<body>
    <div>
        <h1 class="site-page-title">
            Adventure Works Photo Sharing
        </h1>
        <div class="clear-floats" />


        @*<div id="topmenu">
            Zona del menú de navegación
        </div>
        <div id="breadcrumb">
            Zona de mapa del sitio
        </div>*@

        <nav id="topmenu">
            <ul>

                <li><a href="#">@Html.ActionLink("Home", "Index", "Home")</a></li>

                <li><a href="#"></a>@Html.ActionLink("Photos", "Index", "Photo")</li>
            </ul>
        </nav>

        <div>
            @RenderBody()
        </div>

    </div>
</body>
</html>

PhotoSharingApplication/Views/Shared/_PhotoGallery.cshtml
@model IEnumerable<PhotoSharingApplication.Models.Photo>

@foreach (var item in Model)
{

    <div class="photo-index-card">
        <h3>"@item.Title"</h3>

        @if (item.PhotoFile != null)
        {
            <img class="photo-index-card-img" src="@Url.Action("GetImage", "Photo", new { id = item.PhotoID })" />
        }

        <div class="photo-metadata">

            <div>
                <span class="display-label">
                    Created By:
                </span>
                <span class="display-field">
                    @Html.DisplayFor(model => item.UserName)
                </span>
            </div>

            <div>
                <span class="display-label">
                    Created On:
                </span>
                <span class="display-field">
                    @Html.DisplayFor(model => item.CreatedDate)
                </span>
            </div>

        </div>

        @Html.ActionLink("Display", "Display", new { id = item.PhotoID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.PhotoID })

    </div>
}